### ISSUE TITLE
云函数好像没有编译出来

### ISSUE THREAD

**Issue by zaoan660** [r3x5ur/unveilr#105]
### unveilr版本

2.0.1

### 操作系统

windows

### 运行时命令

成功编译了

### 重现步骤

小程序的名字是翻转外语,下载后输入`unveilr 文件名`就可以成功.

### 预期结果

成功反编译

### 实际结果

达到了预期结果

### 其他信息

```
App({
  gData: {},
  onLaunch: function () {
    var e = this,
      n = wx.getStorageSync("logs") || [];
    n.unshift(Date.now()), wx.setStorageSync("logs", n), this.productionTrue();
    var a = this;
    wx.setStorageSync("firstUrl", !1), wx.getBackgroundFetchData({
      fetchType: "pre",
      success: function (e) {
        var n = JSON.parse(e.fetchedData);
        console.log("有没有被调用")
        a.gData.spk = n.spk, a.gData.ak = n.ak, a.gData.aiv = n.aiv, a.gData.thisKeyPair = new t.JSEncrypt({
          default_key_size: 521
        }), a.gData.cpuk = a.gData.thisKeyPair.getPublicKey().replace(/-----BEGIN PUBLIC KEY-----\n/g, "").replace(/\n-----END PUBLIC KEY-----/g, "").replace(/\n/g, ""), a.gData.cprk = a.gData.thisKeyPair.getPrivateKey().replace(/-----BEGIN PUBLIC KEY-----\n/g, "").replace(/\n-----END PUBLIC KEY-----/g, "").replace(/\n/g, "")
      }
    }), wx.login({
      success: function (t) {}
    }), wx.getSetting({
      success: function (t) {
        t.authSetting["scope.userInfo"] && wx.getUserInfo({
          success: function (t) {
            e.globalData.userInfo = t.userInfo, e.userInfoReadyCallback && e.userInfoReadyCallback(t)
          }
        })
      }
    })
  },
```
我尝试得到`wx.getBackgroundFetchData`里的内容,可是我抓不到`wx.getBackgroundFetchData`的包,微信小程序开发文档里写,这是一个预拉取云函数,当用户打开小程序时,微信服务器会首先调用一个后台设置的云函数,然后把返回内容缓存到客户端,`wx.getBackgroundFetchData`是从本地获取.可是如果使用云函数好像会有类似
"""
wx.cloud.init({
        env: 'cloud1-0359uz9ae74f5e7d',
        traceUser: true,
      });
"""
这样的代码.我尝试使用微信小程序开发工具运行反编译的项目代码.`console.log("有没有被调用")`这一句没有被调用.我尝试打印`a.gData.spk`,输出的值是`undefined`

**Comment by r3x5ur** [comment]
这个是授权的问题，你没有权限操作别人的云函数

**Comment by zaoan660** [comment]
可是不只是没法调用,秘钥就好像凭空冒出来的一样.就是我的想法是,假如说小程序没有使用云函数,那`wx.getBackgroundFetchData`是云函数的api应该是使用了云函数,假如说小程序使用了云函数,那又没有`wx.cloud.init`这样的代码初始化环境,`wx.getBackgroundFetchData`可能是不起作用的,假如说它不起作用,那秘钥就像凭空冒出来的一样.我尝试把秘钥等于undefined加密的代码会显示length等于0而报错

**Comment by r3x5ur** [comment]
`getBackgroundFetchData `  这个API 的数据怎么处理的，我这个程序是没办法干预的， 所以你还是得自己想办法解决， 我这个工具是搞不定这种问题的

**Comment by zaoan660** [comment]
好吧,谢谢.学校强制要求每天背些单词,为4,6级做准备.结果自动通过的脚步写不出来😥.谢谢
