### ISSUE TITLE
反编译的文件里有html，app.json反编译后的文件是app-config.json

### ISSUE THREAD

**Issue by nobita0522** [r3x5ur/unveilr#11]
**Describe the bug**

**To Reproduce**/**复现过程**

**Expected behavior**/**预期结果**

**Actual behavior**/**实际结果**

**Screenshots**/**相关截图**

**运行环境、版本信息**<br/>
**Desktop (please complete the following information):**
 - OS:
 - NodeJS:
 - Version

**Additional context**/**其他描述**

**Comment by nobita0522** [comment]
了解了，这是没有完全编译的结果，大佬更新支持一下呢

**Comment by r3x5ur** [comment]
#15 等待发布
