### ISSUE TITLE
[Bug]: 安装报错

### ISSUE THREAD

**Issue by willing555** [r3x5ur/unveilr#117]
### unveilr版本

安装错误

### 操作系统

windows

### 运行时命令

npm i unveilr -g

### 重现步骤

npm i unveilr -g

### 预期结果

npm ERR! code ENOVERSIONS
npm ERR! No versions available for unveilr

npm ERR! A complete log of this run can be found in: D:\work\Node\node_cache\_logs\2023-05-18T03_48_54_018Z-debug-0.log

### 实际结果

npm ERR! code ENOVERSIONS
npm ERR! No versions available for unveilr

npm ERR! A complete log of this run can be found in: D:\work\Node\node_cache\_logs\2023-05-18T03_48_54_018Z-debug-0.log

### 其他信息

npm ERR! code ENOVERSIONS
npm ERR! No versions available for unveilr

npm ERR! A complete log of this run can be found in: D:\work\Node\node_cache\_logs\2023-05-18T03_48_54_018Z-debug-0.log

**Comment by r3x5ur** [comment]
npm 仓库已删除，需要自己使用 `node > 12.0.0` 构建
