### ISSUE TITLE
有重构或者可用版本吗

### ISSUE THREAD

**Issue by yungzhu** [r3x5ur/unveilr#14]
如有，加我微信 yungzhu 感谢

**Comment by r3x5ur** [comment]
。。。 正在努力代码中

**Comment by r3x5ur** [comment]
> 。。。 正在努力撸代码中

**Comment by r3x5ur** [comment]
月底来看，应该有2.0版

**Comment by hanenci1** [comment]
SyntaxError: Unexpected token '}'异常 
大神，这个问题解决了吗？

**Comment by r3x5ur** [comment]
> SyntaxError: Unexpected token '}'异常 大神，这个问题解决了吗？

新版本直接解析语法树，不会有这种问题

**Comment by r3x5ur** [comment]
#15 等待发布
