### ISSUE TITLE
个人原因延期到月底发布，努力中🏃‍♂️🏃‍♂️🏃‍♂️

### ISSUE THREAD

**Issue by r3x5ur** [r3x5ur/unveilr#15]
#13 #12

**Comment by bopo** [comment]
支持一个~

**Comment by Momohanfeng** [comment]
期待，周一见

**Comment by lys623** [comment]
![image](https://user-images.githubusercontent.com/4364314/226074793-b9dd08a5-25ea-42e4-83dc-648a6d5e07d4.png)
新包支持解决这种问题吗？现在主包名字怎么都是数字开头的了？我是在mac上打开微信小程序获取到额路径

**Comment by r3x5ur** [comment]
> ![image](https://user-images.githubusercontent.com/4364314/226074793-b9dd08a5-25ea-42e4-83dc-648a6d5e07d4.png) 新包支持解决这种问题吗？现在主包名字怎么都是数字开头的了？我是在mac上打开微信小程序获取到额路径

可以提供样本吗，我看看咋回事

**Comment by lys623** [comment]
[7.wxapkg.zip](https://github.com/r3x5ur/unveilr/files/11008099/7.wxapkg.zip)
样本是这个

**Comment by lys623** [comment]
> > ![image](https://user-images.githubusercontent.com/4364314/226074793-b9dd08a5-25ea-42e4-83dc-648a6d5e07d4.png) 新包支持解决这种问题吗？现在主包名字怎么都是数字开头的了？我是在mac上打开微信小程序获取到额路径
> 
> 可以提供样本吗，我看看咋回事
[7.wxapkg.zip](https://github.com/r3x5ur/unveilr/files/11008100/7.wxapkg.zip)
样本是这个

**Comment by r3x5ur** [comment]
@lys623 MacOS 是被加密的，暂时先使用 [https://github.com/TinyNiko/mac_wxapkg_decrypt.git](https://github.com/TinyNiko/mac_wxapkg_decrypt.git) 解密一下，后续考虑集成到一起去

**Comment by r3x5ur** [comment]
延期延期到月底，顶不住了
![image](https://user-images.githubusercontent.com/64947085/226221149-09735485-148d-472b-9a52-a5599c44e860.png)

**Comment by lys623** [comment]
> @lys623 你这个样本可以解出来，不会报错 ![image](https://user-images.githubusercontent.com/64947085/226363135-c36f24e7-b873-4c0f-82a9-9f4e4d296ead.png)

大佬用哪个工具解的？
我用 npm i wxapkg-unpacker -g ，后执行 wxupk [path] 解压报错

![image](https://user-images.githubusercontent.com/4364314/226493225-05979b5f-d67a-41ca-ba1b-3a4741881c19.png)

**Comment by r3x5ur** [comment]
@lys623 你先用这个？https://github.com/r3x5ur/unveilr/releases/tag/v1.0.2
下载源码，然后  
`npm install`  
`npx wxupk`

**Comment by r3x5ur** [comment]
**测试版来了，欢迎大哥们提bug**
[unveilr@2.0.0-alpha.0](https://github.com/r3x5ur/unveilr/releases/tag/v2.0.0-alpha.0)

**Comment by hanenci1** [comment]
出个详细的使用教程吧，不会用

**Comment by lys623** [comment]
![image](https://user-images.githubusercontent.com/4364314/227774834-3f4fa4dd-9f95-46fe-b06d-83e05fa0a127.png)
mac上运行不了

![image](https://user-images.githubusercontent.com/4364314/227774846-86cedc00-db34-4b17-9ff6-aa36c5f773ff.png)

**Comment by r3x5ur** [comment]
@lys623 我加了一个 arm架构的macos二进制文件，不知道你能不能使用，如果不行，用 npm安装吧

**Comment by hu185396** [comment]
2.0版本还支持解分包吗？ 看着好像没有-s 命令

**Comment by lys623** [comment]
> @lys623 我加了一个 arm架构的macos二进制文件，不知道你能不能使用，如果不行，用 npm安装吧

![image](https://user-images.githubusercontent.com/4364314/227881447-e2fa6c8b-9d31-49b9-b22f-02e5f7aac866.png)
还是不行，npm怎么安装和使用

**Comment by r3x5ur** [comment]
@lys623 [安装方法](https://github.com/r3x5ur/unveilr#%E5%AE%89%E8%A3%85%E6%96%B9%E6%B3%95)

**Comment by r3x5ur** [comment]
> 

直接解就好了， 不用-s了

**Comment by r3x5ur** [comment]
> 2.0版本还支持解分包吗？ 看着好像没有-s 命令

看文档吧

**Comment by AaronChengHao** [comment]
作者，您好。请问，解包之后，可以在微信开发者工具运行吗？

**Comment by r3x5ur** [comment]
@AaronChengHao 试试不就知道了

**Comment by r3x5ur** [comment]
[v2.0.0-beta.1](https://github.com/r3x5ur/unveilr/releases/tag/v2.0.0-beta.1)
