### ISSUE TITLE
提示 subPackage.pages is not iterable

### ISSUE THREAD

**Issue by linskyFox** [r3x5ur/unveilr#16]
┬ ┬─┐ ┬┌─┐┌─┐┬┌─┌─┐   ┬ ┬┌┐┌┌─┐┌─┐┌─┐┬┌─┌─┐┬─┐
│││┌┴┬┘├─┤├─┘├┴┐│ ┬───│ ││││├─┘├─┤│  ├┴┐├┤ ├┬┘
└┴┘┴ └─┴ ┴┴  ┴ ┴└─┘   └─┘┘└┘┴  ┴ ┴└─┘┴ ┴└─┘┴└─
                      version v1.0.1
                      author @r3x5ur

[INFO]  2023/03/16 09:08:58 wxunpacker Logger level: INFO
[INFO]  2023/03/16 09:08:58 wxunpacker Enabled decrypt mode. wxAppid: wx21c7506e98a2fe75
[INFO]  2023/03/16 09:08:59 wxunpacker Decrypted successful save in D:\小程序\517\decrypted
[INFO]  2023/03/16 09:08:59 wxunpacker Clear old package is turned on.
[INFO]  2023/03/16 09:08:59 wxunpacker Unpack file D:\小程序\517\decrypted\__APP__.wxapkg
[INFO]  2023/03/16 09:08:59 wxunpacker Current package file count: 690
[INFO]  2023/03/16 09:08:59 wxunpacker Current package type is: [APP_SERVICE]
C:\Users\sky\AppData\Roaming\npm\node_modules\wxapkg-unpacker\packages\unpacker\src\wuConfig.js:62
        for (let page of subPackage.pages) {
                                    ^

TypeError: subPackage.pages is not iterable
    at C:\Users\sky\AppData\Roaming\npm\node_modules\wxapkg-unpacker\packages\unpacker\src\wuConfig.js:62:37
    at C:\Users\sky\AppData\Roaming\npm\node_modules\wxapkg-unpacker\packages\unpacker\src\wuLib.js:105:10
    at agent (C:\Users\sky\AppData\Roaming\npm\node_modules\wxapkg-unpacker\packages\unpacker\src\wuLib.js:66:17)
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3)

**Comment by r3x5ur** [comment]
重复 #4
