### ISSUE TITLE
分包可以逆了不？

### ISSUE THREAD

**Issue by zcw-shio** [r3x5ur/unveilr#17]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by r3x5ur** [comment]
当然可以，但是得等哦

**Comment by zcw-shio** [comment]
哈哈哈哈哈 加油

**Comment by r3x5ur** [comment]
#15 等待发布

**Comment by zmc1212** [comment]
大佬 分包可逆啥时候出来
