### ISSUE TITLE
解包出来，js文件是混淆了的

### ISSUE THREAD

**Issue by AaronChengHao** [r3x5ur/unveilr#26]
**复现过程**
使用 wxupk 命令
**预期结果**
js文件是正常的书写格式
**实际结果**
解包出来，js文件是混淆了的
**相关截图**
![image](https://user-images.githubusercontent.com/20119217/226659176-94ad435a-a741-46b9-a5a0-fd20b495a95a.png)

**Comment by r3x5ur** [comment]
emmm 这是另一个问题了

**Comment by r3x5ur** [comment]
文件被混淆了这个是没办法还原的， 
我做的事情是把 wxapkg包 还原成代码，
至于代码是什么样的，看你怎么编译的了，
所以我也是爱莫能助了
