### ISSUE TITLE
TypeError: Cannot read property 'blue' of null

### ISSUE THREAD

**Issue by shaoslu** [r3x5ur/unveilr#27]
大佬您好，我的系统是mac m1，小程序麦当劳的包是在安卓上导出来的，使用您的插件是2.0-beta版本，我在解分包的时候报了下面这个错误，请问知道是什么问题吗？
<img width="832" alt="image" src="https://user-images.githubusercontent.com/11626713/227706972-9ab0fa74-a447-4aa3-a446-ac6c2338f7d9.png">

**Comment by r3x5ur** [comment]
@shaoslu 发我一个样本可以吗，还有你执行的命令

**Comment by shaoslu** [comment]
@r3x5ur 大佬您好，下面截图是我的执行命令，附件里面的 _-1954871067_288 是主包，其他是分包
<img width="1231" alt="image"  src="https://user-images.githubusercontent.com/11626713/227748987-28acc3de-ed53-406d-9704-53b90e5f62f0.png">

[麦当劳wxapkg.zip](https://github.com/r3x5ur/unveilr/files/11070492/wxapkg.zip)

**Comment by r3x5ur** [comment]
@shaoslu 
单独解 _-1954871067_288.wxapkg (主包)
剩下的是插件 我正准备添加支持呢,你就碰到了,等我更新哈

**Comment by shaoslu** [comment]
@r3x5ur 好的谢谢，什么时候支持APP_V3,APP_SUBPACKAGE_V2呢

**Comment by r3x5ur** [comment]
[🔖v2.0.0-alpha.1](https://github.com/r3x5ur/unveilr/releases/tag/v2.0.0-alpha.1)
