### ISSUE TITLE
[Bug] 无入口文件的包无法解析

### ISSUE THREAD

**Issue by Momohanfeng** [r3x5ur/unveilr#29]
**复现过程**
unveilr@2.0.0-alpha.2-win-x64.exe wx 
**预期结果**

**实际结果**
[ERROR] 11:32:53 <GlobalExceptionCaught> Error: GetZArray fail: t is not iterable
    at C:\snapshot\unveilr\dist\parser-70c91931.js:7:473887
    at new Promise (<anonymous>)
    at parserZArray (C:\snapshot\unveilr\dist\parser-70c91931.js:7:473746)
    at Object.V [as parseWxml] (C:\snapshot\unveilr\dist\parser-70c91931.js:7:484828)
    at WxmlParser.parseV1 (C:\snapshot\unveilr\dist\traverse-16b693ce.js:7:24900)
    at C:\snapshot\unveilr\dist\index.js:7:15281
    at Array.forEach (<anonymous>)
    at e (C:\snapshot\unveilr\dist\index.js:7:15215)
    at Object.run (C:\snapshot\unveilr\dist\index.js:7:15842)
    at WorkerPool.<anonymous> (C:\snapshot\unveilr\node_modules\threads\dist\master\pool.js:85:48)
**相关截图**
![image](https://user-images.githubusercontent.com/4652023/227834663-29d8e806-4d11-42b8-9f5c-35b9fa73092c.png)

**运行环境、版本信息**<br/>
 - OS:Windows 10 专业版 19045.2728
 - NodeJS:18.14.1
 - Version：unveilr@2.0.0-alpha.2-win-x64

**其他描述**
实际上并没有 C:\snapshot\路径

**Comment by hanenci1** [comment]
<GlobalExceptionCaught> Error: EMFILE: too many open files,

**Comment by r3x5ur** [comment]
@Momohanfeng 方便提供样本吗？
或者你使用 `--no-parse`参数重新运行一些
然后 打开 `page-frame.html` 告诉我编译器版本`__wcc_version__` 
类似这样的 `__wcc_version__='v0.5vv_20200413_syb_scopedata'`

**Comment by r3x5ur** [comment]
发现了一个 `wcc`版本不能正常解析 `v0.6vv_20170214_fbi`

**Comment by Momohanfeng** [comment]
> wcc_version

--no-parse运行之后没有page-frame.html生成
[yb.zip](https://github.com/r3x5ur/unveilr/files/11076038/yb.zip)

**Comment by r3x5ur** [comment]
@Momohanfeng 
你这个哪搞的包，为啥连入口文件都找不到

**Comment by Momohanfeng** [comment]
> @Momohanfeng 你这个哪搞的包，为啥连入口文件都找不到，我还是第一次见这种样子的 ![image](https://user-images.githubusercontent.com/64947085/227878212-59053b11-ddcf-4947-80bf-9196fea4253d.png)

看了一下以前旧版的提取的page-frame.html中，__wcc_version__='v0.5vv_20200413_syb_scopedata'

**Comment by liuhc2022** [comment]
> @Momohanfeng 方便提供样本吗？ 或者你使用 `--no-parse`参数重新运行一下 然后 打开 `page-frame.html` 告诉我编译器版本`__wcc_version__` 类似这样的 `__wcc_version__='v0.5vv_20200413_syb_scopedata'`

大佬 我这个失败 能帮忙看下吗 谢谢 报错很多 咱也不知道是啥
[wx7162b9b9a0c18563.zip](https://github.com/r3x5ur/unveilr/files/11076513/wx7162b9b9a0c18563.zip)

**Comment by r3x5ur** [comment]
@liuhc2022 也是没有入口文件的
![image](https://user-images.githubusercontent.com/64947085/227890194-690767ae-0cf2-4e95-87d4-6cf464d85b3f.png)

**Comment by liuhc2022** [comment]
> @liuhc2022 也是没有入口文件的 ![image](https://user-images.githubusercontent.com/64947085/227890194-690767ae-0cf2-4e95-87d4-6cf464d85b3f.png)

那入口文件可以从哪儿找到吗

**Comment by r3x5ur** [comment]
![image](https://user-images.githubusercontent.com/64947085/227945368-c1570d70-e9e4-47fe-9863-7a76b094dd7e.png)

**Comment by Momohanfeng** [comment]
> ![image](https://user-images.githubusercontent.com/64947085/227945368-c1570d70-e9e4-47fe-9863-7a76b094dd7e.png)

辛苦了，感谢出新版本，请你喝杯雪王

**Comment by r3x5ur** [comment]
@Momohanfeng 哈哈，感谢支持 :beers:

**Comment by Momohanfeng** [comment]
@r3x5ur 您好，合入 #42 之后，--no-parse 命令可以正确生成page-frame.html。但是
![image](https://user-images.githubusercontent.com/4652023/228449733-d5810534-a1d5-4fb2-ac64-b6672b3d7aa9.png)

**Comment by r3x5ur** [comment]
@Momohanfeng 等我发布更新呢

**Comment by Momohanfeng** [comment]
> @Momohanfeng 等我发布更新呢

已经可以正确进行了，感谢大佬辛苦付出，能力有限，请你再喝个喜茶 @r3x5ur

**Comment by r3x5ur** [comment]
@Momohanfeng 太客气了，哈哈 🍻
