### ISSUE TITLE
[Bug] Error: EMFILE: too many open files

### ISSUE THREAD

**Issue by r3x5ur** [r3x5ur/unveilr#32]
<GlobalExceptionCaught> Error: EMFILE: too many open files,

_Originally posted by @hanenci1 in https://github.com/r3x5ur/unveilr/issues/29#issuecomment-1484521193_

**Comment by hanenci1** [comment]
这个就是解一个出现的

**Comment by hanenci1** [comment]
子包解不出来，

**Comment by hanenci1** [comment]
分包的wxml不出来

**Comment by r3x5ur** [comment]
@hanenci1 是提示 `too many open files` 吗？

**Comment by hanenci1** [comment]
子包解析没有提示错误，但是出来的文件没有wxml

**Comment by hanenci1** [comment]
有page-frame.js这个，但是wxml没有出来

**Comment by r3x5ur** [comment]
提交一个样本我看下呗~

**Comment by hanenci1** [comment]
[_437336288_14.zip](https://github.com/r3x5ur/unveilr/files/11099117/_437336288_14.zip)

**Comment by r3x5ur** [comment]
> [_437336288_14.zip](https://github.com/r3x5ur/unveilr/files/11099117/_437336288_14.zip)

这个不包不能解的问题已经解决了，#47 但是得等我下一次发布版本了

**Comment by hanenci1** [comment]
幸苦大佬，大概啥时候发布

**Comment by hanenci1** [comment]
大佬，能把解包出来的文件发我看下吗？
