### ISSUE TITLE
[Quest]为什么提示 You are trying to save a falsy data

### ISSUE THREAD

**Issue by linskyFox** [r3x5ur/unveilr#34]
![1679909412071](https://user-images.githubusercontent.com/7816103/227901893-61a225b7-8514-4e8d-944c-73e380b06c3e.png)

**Comment by r3x5ur** [comment]
@linskyFox 有些文件路径解析出来是空的，就会有这个提示，问题不大

**Comment by r3x5ur** [comment]
@linskyFox 有些文件路径解析出来是空的，就会有这个提示，问题不大

**Comment by r3x5ur** [comment]
#57
