### ISSUE TITLE
winx64版本下载运行.exe可执行文件闪退

### ISSUE THREAD

**Issue by ColSir** [r3x5ur/unveilr#44]
### unveilr版本

2.0.0

### 操作系统

windows

### 运行时命令

unveilr /path/to/dir

### wcc版本

wcc version is: [v0.xxx]

### 重现步骤(最好能上传反编译失败的样本)

如标题

### 预期结果

如标题

### 实际结果

如标题

### 其他信息

如标题

**Comment by r3x5ur** [comment]
信息太少，没办法复现

**Comment by ColSir** [comment]
博主，我就是正常的下载可执行文件，加压出来运行不了，双击直接闪退，进都进不去就没有其它操作了

**Comment by r3x5ur** [comment]
@ColSir 哈哈，这是一个命令行工具呢，文档有使用方式
