### ISSUE TITLE
[Bug]: unveilr@2.0.0-alpha.3-win-x64 -f 不能format json和wxs文件

### ISSUE THREAD

**Issue by Momohanfeng** [r3x5ur/unveilr#45]
### unveilr版本

unveilr@2.0.0-alpha.3-win-x64 

### NodeJs版本

v18.14.1

### 操作系统

windows

### 运行时命令

unveilr@2.0.0-alpha.3-win-x64.exe wx -f 

### wcc版本

v0.5vv_20200413_syb_scopedata

### 重现步骤(最好能上传反编译失败的样本)

unveilr@2.0.0-alpha.3-win-x64.exe wx -f 之后不format json wxs
[_-310915209_154.zip](https://github.com/r3x5ur/unveilr/files/11099542/_-310915209_154.zip)

### 预期结果

-f 命令可以正确format

### 实际结果

没有format .json .wxs文件

**Comment by r3x5ur** [comment]
@Momohanfeng 感谢老哥提交，要不幸苦你自己改一下？提个pr我合掉？
因为问题也不大

**Comment by Momohanfeng** [comment]
> @Momohanfeng 感谢老哥提交，要不幸苦你自己改一下？提个pr我合掉？ 因为问题也不大

我不会。。。

**Comment by r3x5ur** [comment]
fix by #47
