### ISSUE TITLE
[Quest]为什么提示No task to traverse?

### ISSUE THREAD

**Issue by Esingpawn** [r3x5ur/unveilr#49]
我通过 ` >unveilr wxf7f106e28ce91eb5` 提示了`[WARN] 20:16:42 <Core> No task to traverse`
然后我返回重新 遍历整个目录 `C:\Users\Administrator\Documents\WeChat Files\liyuxin5223872\Applet>cd ..

C:\Users\Administrator\Documents\WeChat Files\liyuxin5223872>unveilr Applet
[WARN] 20:17:32 <Core> No task to traverse`
还是提示这个 
于是我又删除了wx这个文件夹 重新进入小程序并新生成了对应文件夹 仍然遇到一样的错误

**Comment by Esingpawn** [comment]
> @Esingpawn 检查一下你的目录下有没有wxapkg文件

经过检查目录下没有wxapkg文件，微信windows版本号是3.9.9.20。
后通过其他电脑（同版本）获取到有wxapkg。
拉回我PC以后编译，第一次提示no task，我确定有文件后单独把文件拉出，提示wxappid must be requied! 之后直接把wxapkg文件拉在appid文件夹下，没有中间文件夹后成功。
这里可以优化下，检查下下级目录
![image](https://user-images.githubusercontent.com/57138070/228999274-e07fdbe2-fa04-4b12-abd7-01e0934ffbed.png)

**Comment by r3x5ur** [comment]
#51
