### ISSUE TITLE
[Bug]: NodeJs版本安装unveilr  提示'unveilr' 不是内部或外部命令，也不是可运行的程序

### ISSUE THREAD

**Issue by Chendp124** [r3x5ur/unveilr#53]
### unveilr版本

v2.0.0-alpha.3

### NodeJs版本

v18.12.1

### 操作系统

windows

### 运行时命令

E:\unveilr>unveilr --help

### 重现步骤(最好能上传反编译失败的样本)

![image](https://user-images.githubusercontent.com/65335313/229339861-042488b3-cdf0-42d3-8ad9-f53f84521271.png)

### 预期结果

![image](https://user-images.githubusercontent.com/65335313/229339893-db5c40e4-0040-4bd2-9e8a-4ceca5267bde.png)

### 实际结果

![image](https://user-images.githubusercontent.com/65335313/229339891-c29e0b39-4309-483a-b620-29920963cae5.png)

**Comment by r3x5ur** [comment]
试试 npx unveilr发自我的 iPhone在 2023年4月2日，15:51，qq1242592914 ***@***.***> 写道：﻿
unveilr版本
v2.0.0-alpha.3
NodeJs版本
v18.12.1
操作系统
windows
运行时命令
E:\unveilr>unveilr --help
wcc版本
No response
重现步骤(最好能上传反编译失败的样本)

预期结果

实际结果

其他信息
No response

**Comment by r3x5ur** [comment]
这是你电脑环境的问题，你尝试使用 `npx unveilr --help`
