### ISSUE TITLE
[ERROR] 17:06:55 <Exception> a: File /Users/path/_1123949441_868.wxapkg source directory not found

### ISSUE THREAD

**Issue by r3x5ur** [r3x5ur/unveilr#67]
[ERROR] 17:06:55 <Exception> a: File /Users/path/_1123949441_868.wxapkg source directory not found

你好，我把小程序目录下面的包全部拷贝过来，执行`uvr path `出现这个错误。这个是什么原因造成的呢？我仔细检查过，所有包都拷贝过来了。

_Originally posted by @kainstan in https://github.com/r3x5ur/unveilr/discussions/24#discussioncomment-5541483_

**Comment by r3x5ur** [comment]
@kainstan 把发生错误的包样本提供一下？

**Comment by kainstan** [comment]
@r3x5ur 
[sample.zip](https://github.com/r3x5ur/unveilr/files/11175640/sample.zip)
不管是单独解包还是全部解包，都是这个文件出现错误。

**Comment by r3x5ur** [comment]
![image](https://user-images.githubusercontent.com/64947085/230557518-057cb41d-fde1-4650-9768-935d8c5e5967.png)

@kainstan `framework `不能解析，使用 `--no-parse` 参数

**Comment by r3x5ur** [comment]
`framework` 是安卓端运行依赖，不是真正的小程序代码哦

**Comment by r3x5ur** [comment]
`Running the framework does not require unpacking`

**Comment by kainstan** [comment]
@r3x5ur 所以不需要解包这个文件吗？解包其他文件，然后在微信小程序开发工具上运行就行吗？

**Comment by r3x5ur** [comment]
稍微留意一下，一般得小程序不会超过10MB的，你这个18Mb

**Comment by r3x5ur** [comment]
> @r3x5ur 所以不需要解包这个文件吗？解包其他文件，然后在微信小程序开发工具上运行就行吗？

是的， 直接把这个删掉，没用的


报错也算是个bug吧
不应该报错的
我有空处理一下这个

**Comment by kainstan** [comment]
还有个问题，好像是小程序出新版本了，这个解包工具直接报无效的包

**Comment by kainstan** [comment]
_-1129615052_642.wxapkg is an invalid package!

我这边上传一下样本

**Comment by kainstan** [comment]
[sample2.zip](https://github.com/r3x5ur/unveilr/files/11176738/sample2.zip)
目前解析出来会出`invalid package!`错误

**Comment by r3x5ur** [comment]
![image](https://user-images.githubusercontent.com/64947085/230560639-c7a3140c-a593-4470-9f53-54f6cb147050.png)

我刚刚测试是可以的啊

**Comment by kainstan** [comment]
我是用node18.14.2版本在mac x86编译的。   如果用release已经编译好的win x86确实没问题。谢谢！

**Comment by kainstan** [comment]
建议作者在README上追加node及其他运行时环境的版本，谢谢

**Comment by kainstan** [comment]
> 稍微留意一下，一般得小程序不会超过10MB的，你这个18Mb

@r3x5ur 感谢
