### ISSUE TITLE
反编译解分包时提示请通过 -s 参数指定存放路径后重试

### ISSUE THREAD

**Issue by ChicBrother** [r3x5ur/unveilr#7]
大佬，新版本能很好地反编译主包的内容，但发现在解分包时会出错

D:/Documents/WeChat Files/Applet/wx74ec617ga0a6c8e2/929 目录文件：
![image](https://user-images.githubusercontent.com/15015547/222169847-6dbaf4f1-f9c5-4597-814c-a9556cd29eac.png)

运行命令（小程序PC端）:
yarn wxupk "D:/Documents/WeChat Files/Applet/wx74ec617ga0a6c8e2/929" -i wx74ec617ga0a6c8e2 -l DEBUG

错误提示：

[DEBUG] 2023/03/01 22:27:22 wxunpacker Guess wxss(first turn)...
[DEBUG] 2023/03/01 22:27:22 wxunpacker do css runVm: D:\Documents\WeChat Files\Applet\wx74ec617ga0a6c8e2\929\decrypted\__APP__\app.wxss
[DEBUG] 2023/03/01 22:27:22 wxunpacker Import count info: %j {}
[DEBUG] 2023/03/01 22:27:22 wxunpacker Guess wxss(first turn) done.
Generate wxss(second turn)...
[DEBUG] 2023/03/01 22:27:22 wxunpacker do css runVm: D:\Documents\WeChat Files\Applet\wx74ec617ga0a6c8e2\929\decrypted\__APP__\app.wxss
[DEBUG] 2023/03/01 22:27:22 wxunpacker Generate wxss(second turn) done.
Save wxss...
[DEBUG] 2023/03/01 22:27:22 wxunpacker saveDir: D:\Documents\WeChat Files\Applet\wx74ec617ga0a6c8e2\929\decrypted\__APP__
[DEBUG] 2023/03/01 22:27:23 wxunpacker Unpacked success: D:\Documents\WeChat Files\Applet\wx74ec617ga0a6c8e2\929\decrypted\__APP__.wxapkg
[DEBUG] 2023/03/01 22:27:23 wxunpacker =================================processed===================================

[DEBUG] 2023/03/01 22:27:23 wxunpacker ===============================before-process=================================
[DEBUG] 2023/03/01 22:27:23 wxunpacker Already cleaned old package D:\Documents\WeChat Files\Applet\wx74ec617ga0a6c8e2\929\decrypted\_modules_shoppingMall_
[INFO]  2023/03/01 22:27:23 wxunpacker Unpack file D:\Documents\WeChat Files\Applet\wx74ec617ga0a6c8e2\929\decrypted\_modules_shoppingMall_.wxapkg
[INFO]  2023/03/01 22:27:23 wxunpacker Current package file count: 3
[INFO]  2023/03/01 22:27:23 wxunpacker Current package type is: [APP_SERVICE]
[DEBUG] 2023/03/01 22:27:23 wxunpacker Split and make up done.
[DEBUG] 2023/03/01 22:27:23 wxunpacker Delete files...
[DEBUG] 2023/03/01 22:27:23 wxunpacker Unpacked success: D:\Documents\WeChat Files\Applet\wx74ec617ga0a6c8e2\929\decrypted\_modules_shoppingMall_.wxapkg
[DEBUG] 2023/03/01 22:27:23 wxunpacker =================================processed===================================

[DEBUG] 2023/03/01 22:27:23 wxunpacker ===============================before-process=================================
[DEBUG] 2023/03/01 22:27:23 wxunpacker Already cleaned old package D:\Documents\WeChat Files\Applet\wx74ec617ga0a6c8e2\929\decrypted\_modules_orderList_
[INFO]  2023/03/01 22:27:23 wxunpacker Unpack file D:\Documents\WeChat Files\Applet\wx74ec617ga0a6c8e2\929\decrypted\_modules_orderList_.wxapkg
**[ERROR] 2023/03/01 22:27:23 wxunpacker 检测到此包是分包后的子包, 请通过 -s 参数指定存放路径后重试, 如 node wuWxapkg.js -s=/xxx/xxx ./testpkg/test-pkg-sub.wxapkg**
[DEBUG] 2023/03/01 22:27:23 wxunpacker Deleted. File done.
[INFO]  2023/03/01 22:27:23 wxunpacker Current package file count: 3
[INFO]  2023/03/01 22:27:23 wxunpacker Current package type is: [APP_SERVICE]
**[ERROR] 2023/03/01 22:27:23 wxunpacker 检测到此包是分包后的子包, 请通过 -s 参数指定存放路径后重试, 如 node wuWxapkg.js -s=/xxx/xxx ./testpkg/test-pkg-sub.wxapkg**
Done in 4.83s.+

**Comment by r3x5ur** [comment]
@ChicBrother 
感谢提交，正在解决中

**Comment by r3x5ur** [comment]
#15 等待发布
