### ISSUE TITLE
[Bug]: Error: EMFILE: too many open files

### ISSUE THREAD

**Issue by PuppetWen** [r3x5ur/unveilr#75]
### unveilr版本

2.0.0-beta.1

### NodeJs版本

v16.0.0

### 操作系统

windows

### 运行时命令

uvr wx ./ -i 微信appid

### wcc版本

v0.5vv_20200413_syb_scopedata

### 重现步骤(最好能上传反编译失败的样本)

uvr wx ./ -i 微信appid
解包所有包时

### 预期结果

 解包完成

### 实际结果

![image](https://user-images.githubusercontent.com/121593186/231336969-129e2942-b423-454e-b013-d69f2f6e9b3f.png)

Error: EMFILE: too many open files, open 'F:\MiniProgram\MiniProgram-tools\test-xx\__APP__\hotel\components\custom-nav\common.wxss'

**Comment by r3x5ur** [comment]
上传样本

**Comment by PuppetWen** [comment]
请问这个情况正常吗，要是正常的话，就可能是我这边操作失误了

**Comment by r3x5ur** [comment]
> 

不正常， 旧版本已经解决过这个问题

**Comment by PuppetWen** [comment]
[wxde8ac0a21135c07d.zip](https://github.com/r3x5ur/unveilr/files/11208927/wxde8ac0a21135c07d.zip)

**Comment by r3x5ur** [comment]
@PuppetWen 一个小程序这么多文件。。。内存顶得住嘛

**Comment by r3x5ur** [comment]
@PuppetWen 你这不止一个小程序吧，我看着不对劲呢

**Comment by PuppetWen** [comment]
是一个小程序，，，只不过是某团(哭笑.jpg)

**Comment by r3x5ur** [comment]
@PuppetWen 

这是电脑扛不住，电脑配置好的能解开
群里有好几个人解出来了 1万多个文件
电脑带不动你就只能一个一个解了

**Comment by PuppetWen** [comment]
好吧，回头换64g的去，
一个一个解，目录在自己手动合并吗

**Comment by r3x5ur** [comment]
@PuppetWen 是的

**Comment by PuppetWen** [comment]
好的，谢谢大佬
