### ISSUE TITLE
提示Magic Number is not correct!

### ISSUE THREAD

**Issue by liaosunny123** [r3x5ur/unveilr#8]
**Describe the bug**
提示Magic Number is not correct!

**To Reproduce**/**复现过程**
npx wxupk "path" -i wx72ds...

**Actual behavior**/**实际结果**

[INFO]  2023/03/06 10:05:30 wxunpacker Logger level: INFO
[INFO]  2023/03/06 10:05:30 wxunpacker Enabled decrypt mode. wxAppid: wx72ds...
[INFO]  2023/03/06 10:05:30 wxunpacker Decrypted successful save in path\101\decrypted
[INFO]  2023/03/06 10:05:30 wxunpacker Clear old package is turned on.
[INFO]  2023/03/06 10:05:30 wxunpacker Unpack file path\101\decrypted\__WITHOUT_MULTI_PLUGINCODE__.wxapkg
C:\Users\user\AppData\Roaming\npm\node_modules\wxapkg-unpacker\packages\unpacker\src\wuWxapkg.js:24
  if (firstMark !== 0xbe || lastMark !== 0xed) throw Error('Magic number is not correct!')
                                               ^

Error: Magic number is not correct!
    at header (C:\Users\user\AppData\Roaming\npm\node_modules\wxapkg-unpacker\packages\unpacker\src\wuWxapkg.js:24:54)
    at C:\Users\user\AppData\Roaming\npm\node_modules\wxapkg-unpacker\packages\unpacker\src\wuWxapkg.js:224:42
    at C:\Users\user\AppData\Roaming\npm\node_modules\wxapkg-unpacker\packages\unpacker\src\wuLib.js:105:10
    at agent (C:\Users\user\AppData\Roaming\npm\node_modules\wxapkg-unpacker\packages\unpacker\src\wuLib.js:66:17)
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3)

Node.js v18.13.0

**Screenshots**/**相关截图**

**运行环境、版本信息**<br/>
**Desktop (please complete the following information):**
 - OS:Windows 11 x64
 - NodeJS: v18.13.0

**Comment by nobita0522** [comment]
同样，请问如何处理的

**Comment by r3x5ur** [comment]
这种问题可能是解密失败，可以提供以下样本吗

**Comment by nobita0522** [comment]
> 这种问题可能是解密失败，可以提供以下样本吗

已经解决了，谢谢。但是现在又出现了新的问题，反编译出来的文件里尽然后html，然后没有app.json，而是app-config.json

**Comment by Leepay** [comment]
> 同样，请问如何处理的

添加-i参数，输入小程序的app-id

**Comment by liaosunny123** [comment]
> > 这种问题可能是解密失败，可以提供以下样本吗
> 
> 已经解决了，谢谢。但是现在又出现了新的问题，反编译出来的文件里居然有html，且没有app.json，看了一下变成了app-config.json

请问怎么解决的？

**Comment by liaosunny123** [comment]
> 这种问题可能是解密失败，可以提供以下样本吗

有邮箱吗，我可以发给你

**Comment by r3x5ur** [comment]
@liaosunny123  `2352327206@qq.com`
