### ISSUE TITLE
[Bug]: [ WXSS 文件编译错误] ./uview-ui/components/u-parse/libs/trees.wxss  unexpected token "$"

### ISSUE THREAD

**Issue by ccfleaf** [r3x5ur/unveilr#90]
### unveilr版本

2.0.0-beta.1

### NodeJs版本

v14.17.6

### 操作系统

windows

### 运行时命令

unveilr wx -i wx5d334fc48dafd33f ./

### 重现步骤(最好能上传反编译失败的样本)

![image](https://user-images.githubusercontent.com/23294361/232713693-24f4220d-1aab-40b3-a267-cc3051f1559c.png)
导入微信开发工具后，只出了上面的错。界面一片空白，没有出现小程序显示的内容

### 预期结果

小程序界面能呈现

### 实际结果

微信开发工具里界面是空白

**Comment by r3x5ur** [comment]
提供一下样本

**Comment by ccfleaf** [comment]
路特斯小程序

**Comment by ilizhu** [comment]
![image](https://user-images.githubusercontent.com/37323899/233288003-14b4452c-b8b4-4206-9d3a-5a0ce7908b7f.png)
此处改为content:""

**Comment by r3x5ur** [comment]
怎么运行不再我的处理范围之内
