### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by 19373842811** [r3x5ur/unveilr#97]
### unveilr版本

2.0.1

### 操作系统

windows

### 运行时命令

npx unveilr --help

### 重现步骤

npm ERR! could not determine executable to run

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\戴\AppData\Local\npm-cache\_logs\2023-04-27T10_05_34_190Z-debug-0.log

### 预期结果

npm ERR! could not determine executable to run

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\戴\AppData\Local\npm-cache\_logs\2023-04-27T10_05_34_190Z-debug-0.log

### 实际结果

npm ERR! could not determine executable to run

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\戴\AppData\Local\npm-cache\_logs\2023-04-27T10_05_34_190Z-debug-0.log

### 其他信息

大佬unveilr的命令都不能用，是我本地环境的问题吗

**Comment by coolcooldeboy** [comment]
npm包已经不再提供了，到release里下载可执行文件执行

**Comment by r3x5ur** [comment]
从[下载地址](https://github.com/r3x5ur/unveilr/releases)下载对应操作系统的可执行文件

**Comment by ekko-zhao** [comment]
> 从[下载地址](https://github.com/r3x5ur/unveilr/releases)下载对应操作系统的可执行文件

release里面的东西都删了。请问下作者现在应该如何获取啊？
